services:
  chillstudy_db:
    container_name: chillstudy_db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ChillStudy_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ChillStudy_db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  chillstudy_app:
    container_name: chillstudy_app
    image: crud-java:1.0
    build: .
    ports:
      - 8081:8080
    depends_on:
      chillstudy_db:
        condition: service_healthy
