version: "3.9"

services:
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      java_db:
        condition: service_healthy
